name: Upate

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Copy
    runs-on: ubuntu-latest
    steps:

    # checkout paketo github-config as src-repo
    - name: Checkout paketo github-config repo
      uses: actions/checkout@v2
      with:
        ref: copy-action
        repository: joshzarrabi/github-config
        path: config-repo

    # checkout this repo
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: current-repo

    - name: Run the copy action
      uses: config-repo/actions/copy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        config-repo: config-repo
        current-repo: current-repo
        config-path: "/implementation"
        ssh-private-key: ${{ secrets.my_deploy_key_private }}
      id: do-copy
